# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfg', '0002_block_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAndBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sfg.Patient')),
                ('PATIENT_BLOCK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sfg.Block')),
            ],
        ),
    ]
